use_frameworks!

platform :ios, '10.0'

target 'MKLoRaWAN-MTE_Example' do
  pod 'MKLoRaWAN-MTE', :path => '../'

  target 'MKLoRaWAN-MTE_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
